plugins {
    id 'java'
    id 'org.springframework.boot' version '3.2.4'
    id 'io.spring.dependency-management' version '1.1.4'
}

group = 'com.adarsh'
version = '0.0.1-SNAPSHOT'
description = 'RideBooking-SocketService'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(18)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    implementation 'org.apache.httpcomponents.client5:httpclient5'
    implementation 'org.apache.httpcomponents.core5:httpcore5'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'com.adarsh:RideBooking-EntityService:0.0.6-SNAPSHOT'

    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:4.1.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
